[2025-06-08 19:47:32,033][loader.processor][INFO] - Processing 50 images...
[2025-06-08 19:47:55,326][loader.processor][INFO] - Std_mean estimation for 50 images...
[2025-06-08 19:48:01,101][__main__][INFO] - Starting training pipeline...
[2025-06-08 19:48:01,101][__main__][INFO] - 
Configuration:
[2025-06-08 19:48:01,102][__main__][INFO] - data_dir: D:\Data\CAUSE_data\limestone
dataset: limestone_patches
n_classes: 2
is_not_ready: true
standardization: true
std_mean_path: D:\Data\CAUSE_data\limestone\limestone_std_mean
ckpt: C:/t4_old_very/tomograph4/Scripts/analytics_2/checkpoints/dino_vit_base_8.pth
num_codebook: 2048
reduced_dim: 90
projection_dim: 2048
run_name: train_dinov2
dim: 768
num_queries: 4556
device: cuda
distributed: false
load_segment: false
load_cluster: false
mediator_epoch: 1
front_epoch: 2
fine_tune_epoch: 5
batch_size: 16
learning_rate: 0.001
num_workers: 2
thresh_pos: 0.3
thresh_neg: 0.1
temp: 0.1
grid: true
degree_of_sampling: 2
patch_size: 540
train_resolution: 540
patches_shape:
- 5
- 5
overlap_fraction: 0.2
max_images: 50
gpu: '0'
port: '12355'

[2025-06-08 19:48:01,104][__main__][INFO] - -------------Train Mediator-------------
[2025-06-08 19:48:38,283][__main__][ERROR] - Error in Train Mediator: CUDA out of memory. Tried to allocate 72.38 GiB (GPU 0; 15.99 GiB total capacity; 1021.95 MiB already allocated; 13.46 GiB free; 1.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2025-06-08 19:48:38,503][__main__][INFO] - -------------Train Front-------------
[2025-06-08 19:48:39,493][__main__][INFO] - -------------Fine Tune-------------
[2025-06-08 19:48:40,430][__main__][ERROR] - Error in Fine Tune: [Errno 2] No such file or directory: 'CAUSE\\limestone_patches\\dino_vit_base_8\\train_dinov2\\segment_tr.pth'
[2025-06-08 19:48:40,431][__main__][INFO] - -------------Inference-------------
[2025-06-08 19:48:41,447][__main__][ERROR] - Error in Inference: [Errno 2] No such file or directory: 'CAUSE\\limestone_patches\\dino_vit_base_8\\train_dinov2\\segment_tr.pth'
